config:
  base_directory: public/images
  css_output: tmp/css_sprite.css
  
images:
  - description: Stars with transparency
    sources:
      - sc-mcstars0.png
      - sc-mcstars1.png
      - sc-mcstars2.png
      - sc-mcstars3.png
    target: stars_png_with_transparency.png
    align: horizontal
    spaced_by: 50
  
  - description: Stars as JPEG
    sources:
      - sc-0.jpg
      - sc-1.jpg
      - sc-2.jpg
      - sc-3.jpg
    target: stars_as_jpg.jpg
    align: vertical
    spaced_by: 50